const languages = ['en', 'es', 'fr', 'de', 'pt', 'ru', 'zh', 'ja', 'ko', 'ar', 'hi'];
const rows: Record<string, string[]> = {
  'Vista': ['View', 'Ver', 'Affichage', 'Ansicht', 'Ver', 'Вид', '视图', '表示', '보기', 'عرض', 'दृश्य'],
  'Aiuto': ['Help', 'Ayuda', 'Aide', 'Hilfe', 'Ajuda', 'Справка', '帮助', 'ヘルプ', '도움말', 'مساعدة', 'सहायता'],
  'Esci': ['Quit', 'Salir', 'Quitter', 'Beenden', 'Sair', 'Выход', '退出', '終了', '종료', 'خروج', 'बाहर निकलें'],
  'Dimensioni reali': ['Actual size', 'Tamaño real', 'Taille réelle', 'Originalgröße', 'Tamanho real', 'Фактический размер', '实际大小', '実際のサイズ', '실제 크기', 'الحجم الفعلي', 'वास्तविक आकार'],
  'Zoom sulla selezione': ['Zoom to selection', 'Ampliar selección', 'Zoom sur la sélection', 'Auswahl vergrößern', 'Ampliar seleção', 'Масштаб по выделению', '缩放到选区', '選択範囲を拡大', '선택 영역 확대', 'تكبير التحديد', 'चयन पर ज़ूम करें'],
  'Mostra/nascondi libreria e pannello': ['Show/hide library and panel', 'Mostrar/ocultar biblioteca y panel', 'Afficher/masquer la bibliothèque et le panneau', 'Bibliothek und Bedienfeld ein-/ausblenden', 'Mostrar/ocultar biblioteca e painel', 'Показать/скрыть библиотеку и панель', '显示/隐藏素材库和面板', 'ライブラリとパネルの表示切替', '라이브러리 및 패널 표시/숨기기', 'إظهار/إخفاء المكتبة واللوحة', 'लाइब्रेरी और पैनल दिखाएँ/छिपाएँ'],
  'Mostra/nascondi griglia': ['Show/hide grid', 'Mostrar/ocultar cuadrícula', 'Afficher/masquer la grille', 'Raster ein-/ausblenden', 'Mostrar/ocultar grelha', 'Показать/скрыть сетку', '显示/隐藏网格', 'グリッドの表示切替', '격자 표시/숨기기', 'إظهار/إخفاء الشبكة', 'ग्रिड दिखाएँ/छिपाएँ'],
  'Schermo intero': ['Full screen', 'Pantalla completa', 'Plein écran', 'Vollbild', 'Ecrã inteiro', 'Полный экран', '全屏', 'フルスクリーン', '전체 화면', 'ملء الشاشة', 'पूर्ण स्क्रीन'],
  'Strumenti di sviluppo': ['Developer tools', 'Herramientas de desarrollo', 'Outils de développement', 'Entwicklerwerkzeuge', 'Ferramentas de desenvolvimento', 'Инструменты разработчика', '开发者工具', '開発者ツール', '개발자 도구', 'أدوات المطور', 'डेवलपर उपकरण'],
  'Non salvare': ['Don’t save', 'No guardar', 'Ne pas enregistrer', 'Nicht speichern', 'Não guardar', 'Не сохранять', '不保存', '保存しない', '저장 안 함', 'عدم الحفظ', 'न सहेजें'],
  'Salvare le modifiche prima di chiudere?': ['Save changes before closing?', '¿Guardar los cambios antes de cerrar?', 'Enregistrer les modifications avant de fermer ?', 'Änderungen vor dem Schließen speichern?', 'Guardar as alterações antes de fechar?', 'Сохранить изменения перед закрытием?', '关闭前保存更改？', '閉じる前に変更を保存しますか？', '닫기 전에 변경 사항을 저장할까요?', 'هل تريد حفظ التغييرات قبل الإغلاق؟', 'बंद करने से पहले बदलाव सहेजें?'],
  'Se non salvi, le modifiche andranno perse.': ['Unsaved changes will be lost.', 'Los cambios sin guardar se perderán.', 'Les modifications non enregistrées seront perdues.', 'Nicht gespeicherte Änderungen gehen verloren.', 'As alterações não guardadas serão perdidas.', 'Несохранённые изменения будут потеряны.', '未保存的更改将丢失。', '保存しない変更は失われます。', '저장하지 않은 변경 사항은 사라집니다.', 'ستفقد التغييرات غير المحفوظة.', 'बिना सहेजे बदलाव खो जाएँगे।'],
  'Impossibile aprire il file': ['Unable to open file', 'No se puede abrir el archivo', 'Impossible d’ouvrir le fichier', 'Datei kann nicht geöffnet werden', 'Não foi possível abrir o ficheiro', 'Не удалось открыть файл', '无法打开文件', 'ファイルを開けません', '파일을 열 수 없습니다', 'تعذر فتح الملف', 'फ़ाइल नहीं खुल सकी'],
  'Immagine SVG': ['SVG image', 'Imagen SVG', 'Image SVG', 'SVG-Bild', 'Imagem SVG', 'Изображение SVG', 'SVG 图像', 'SVG 画像', 'SVG 이미지', 'صورة SVG', 'SVG चित्र'],
  'Documento PDF': ['PDF document', 'Documento PDF', 'Document PDF', 'PDF-Dokument', 'Documento PDF', 'Документ PDF', 'PDF 文档', 'PDF 文書', 'PDF 문서', 'مستند PDF', 'PDF दस्तावेज़'],
  'Immagine PNG': ['PNG image', 'Imagen PNG', 'Image PNG', 'PNG-Bild', 'Imagem PNG', 'Изображение PNG', 'PNG 图像', 'PNG 画像', 'PNG 이미지', 'صورة PNG', 'PNG चित्र'],
  'Codice TikZ': ['TikZ code', 'Código TikZ', 'Code TikZ', 'TikZ-Code', 'Código TikZ', 'Код TikZ', 'TikZ 代码', 'TikZ コード', 'TikZ 코드', 'كود TikZ', 'TikZ कोड'],
  'Cartella del paper': ['Paper folder', 'Carpeta del artículo', 'Dossier de l’article', 'Publikationsordner', 'Pasta do artigo', 'Папка статьи', '论文文件夹', '論文フォルダー', '논문 폴더', 'مجلد الورقة العلمية', 'शोधपत्र फ़ोल्डर'],
  'Scegli la cartella del paper: quella con il file .tex principale': ['Choose the paper folder containing the main .tex file', 'Elige la carpeta del artículo que contiene el archivo .tex principal', 'Choisissez le dossier de l’article contenant le fichier .tex principal', 'Wähle den Ordner mit der Hauptdatei im .tex-Format', 'Escolhe a pasta do artigo que contém o ficheiro .tex principal', 'Выберите папку статьи с основным файлом .tex', '选择包含主 .tex 文件的论文文件夹', 'メインの .tex ファイルがある論文フォルダーを選択', '기본 .tex 파일이 있는 논문 폴더를 선택하세요', 'اختر مجلد الورقة الذي يحتوي على ملف .tex الرئيسي', 'मुख्य .tex फ़ाइल वाला शोधपत्र फ़ोल्डर चुनें'],
  'Usa questa cartella': ['Use this folder', 'Usar esta carpeta', 'Utiliser ce dossier', 'Diesen Ordner verwenden', 'Usar esta pasta', 'Использовать эту папку', '使用此文件夹', 'このフォルダーを使用', '이 폴더 사용', 'استخدام هذا المجلد', 'यह फ़ोल्डर इस्तेमाल करें'],
  'Scegli (o crea) la cartella del progetto: le figure .hfig al suo interno ne faranno parte.': ['Choose or create the project folder. Its .hfig figures will belong to the project.', 'Elige o crea la carpeta del proyecto. Las figuras .hfig que contenga formarán parte de él.', 'Choisissez ou créez le dossier du projet. Les figures .hfig qu’il contient en feront partie.', 'Wähle oder erstelle den Projektordner. Die enthaltenen .hfig-Abbildungen gehören zum Projekt.', 'Escolhe ou cria a pasta do projeto. As figuras .hfig que contém farão parte dele.', 'Выберите или создайте папку проекта. Фигуры .hfig в ней войдут в проект.', '选择或创建项目文件夹，其中的 .hfig 图形将属于该项目。', 'プロジェクトのフォルダーを選択または作成します。中の .hfig 図がプロジェクトに含まれます。', '프로젝트 폴더를 선택하거나 만드세요. 폴더 안의 .hfig 그림이 프로젝트에 포함됩니다.', 'اختر مجلد المشروع أو أنشئه. ستنضم الرسوم بصيغة .hfig الموجودة فيه إلى المشروع.', 'प्रोजेक्ट फ़ोल्डर चुनें या बनाएँ। उसमें मौजूद .hfig चित्र प्रोजेक्ट का हिस्सा होंगे।'],
};
export const nativeMessages: Record<string, Record<string, string>> = Object.fromEntries(
  languages.map((language, index) => [language, Object.fromEntries(Object.entries(rows).map(([source, translations]) => [source, translations[index]]))]),
);
