// Order: en, es, fr, de, pt, ru, zh, ja, ko, ar, hi. Italian is the source language.
const languages = ['en', 'es', 'fr', 'de', 'pt', 'ru', 'zh', 'ja', 'ko', 'ar', 'hi'] as const;
const rows: Record<string, string[]> = {
  'Profilo utente': ['User profile', 'Perfil de usuario', 'Profil utilisateur', 'Benutzerprofil', 'Perfil de utilizador', 'Профиль пользователя', '用户资料', 'ユーザープロフィール', '사용자 프로필', 'الملف الشخصي', 'उपयोगकर्ता प्रोफ़ाइल'],
  'Personalizza il tuo spazio di lavoro.': ['Make your workspace your own.', 'Personaliza tu espacio de trabajo.', 'Personnalisez votre espace de travail.', 'Gestalte deinen Arbeitsbereich.', 'Personaliza o teu espaço de trabalho.', 'Настройте своё рабочее пространство.', '个性化你的工作区。', 'ワークスペースを自分好みに。', '나만의 작업 공간을 설정하세요.', 'خصّص مساحة عملك.', 'अपने कार्यक्षेत्र को अपनी पसंद के अनुसार बनाएँ।'],
  'Salvato su questo dispositivo, senza account o password.': ['Saved on this device, without an account or password.', 'Guardado en este dispositivo, sin cuenta ni contraseña.', 'Enregistré sur cet appareil, sans compte ni mot de passe.', 'Auf diesem Gerät gespeichert, ohne Konto oder Passwort.', 'Guardado neste dispositivo, sem conta nem palavra-passe.', 'Сохраняется на этом устройстве, без аккаунта и пароля.', '保存在此设备上，无需账户或密码。', 'アカウントやパスワードなしで、この端末に保存されます。', '계정이나 비밀번호 없이 이 기기에 저장됩니다.', 'محفوظ على هذا الجهاز، دون حساب أو كلمة مرور.', 'बिना खाते या पासवर्ड के इस डिवाइस पर सहेजा जाता है।'],
  'Il nome viene mostrato nei commenti e nella collaborazione.': ['Your name appears in comments and collaboration.', 'Tu nombre aparece en los comentarios y en la colaboración.', 'Votre nom apparaît dans les commentaires et la collaboration.', 'Dein Name erscheint in Kommentaren und bei der Zusammenarbeit.', 'O teu nome aparece nos comentários e na colaboração.', 'Имя отображается в комментариях и при совместной работе.', '你的姓名会显示在评论和协作中。', '名前はコメントや共同作業に表示されます。', '이름은 댓글과 공동 작업에 표시됩니다.', 'يظهر اسمك في التعليقات والتعاون.', 'आपका नाम टिप्पणियों और सहयोग में दिखाई देता है।'],
  'Colore del profilo': ['Profile color', 'Color del perfil', 'Couleur du profil', 'Profilfarbe', 'Cor do perfil', 'Цвет профиля', '资料颜色', 'プロフィールの色', '프로필 색상', 'لون الملف الشخصي', 'प्रोफ़ाइल का रंग'],
  'Verde acqua': ['Teal', 'Verde azulado', 'Bleu-vert', 'Blaugrün', 'Verde-azulado', 'Бирюзовый', '青绿色', '青緑', '청록색', 'أخضر مزرق', 'नीला-हरा'],
  'Rosa': ['Rose', 'Rosa', 'Rose', 'Rosa', 'Rosa', 'Розовый', '玫瑰色', 'ローズ', '분홍색', 'وردي', 'गुलाबी'],
  'Ambra': ['Amber', 'Ámbar', 'Ambre', 'Bernstein', 'Âmbar', 'Янтарный', '琥珀色', '琥珀色', '호박색', 'كهرماني', 'अंबर'],
  'Preferenze personali': ['Personal preferences', 'Preferencias personales', 'Préférences personnelles', 'Persönliche Einstellungen', 'Preferências pessoais', 'Личные настройки', '个人偏好', '個人設定', '개인 설정', 'التفضيلات الشخصية', 'व्यक्तिगत पसंद'],
  'Le tue scelte vengono ricordate alla prossima apertura.': ['Your choices are remembered next time you open the app.', 'Tus elecciones se recuerdan la próxima vez que abras la app.', 'Vos choix sont conservés pour la prochaine ouverture.', 'Deine Auswahl bleibt beim nächsten Öffnen erhalten.', 'As tuas escolhas são lembradas na próxima abertura.', 'Ваш выбор сохранится до следующего запуска.', '下次打开应用时会记住你的选择。', '次回アプリを開いたときも設定が維持されます。', '다음에 앱을 열 때 선택한 설정이 유지됩니다.', 'يتم تذكّر اختياراتك عند فتح التطبيق مجددًا.', 'अगली बार ऐप खोलने पर आपकी पसंद याद रखी जाती है।'],
  'Griglia del foglio': ['Canvas grid', 'Cuadrícula del lienzo', 'Grille du canevas', 'Zeichenflächenraster', 'Grelha da tela', 'Сетка холста', '画布网格', 'キャンバスのグリッド', '캔버스 격자', 'شبكة اللوحة', 'कैनवास ग्रिड'],
  'Linee': ['Lines', 'Líneas', 'Lignes', 'Linien', 'Linhas', 'Линии', '线条', '線', '선', 'خطوط', 'रेखाएँ'],
  'Croci': ['Crosses', 'Cruces', 'Croix', 'Kreuze', 'Cruzes', 'Крестики', '十字', '十字', '십자', 'تقاطعات', 'क्रॉस'],
  'Pacchetti installati': ['Installed packages', 'Paquetes instalados', 'Paquets installés', 'Installierte Pakete', 'Pacotes instalados', 'Установленные пакеты', '已安装的扩展包', 'インストール済みパッケージ', '설치된 패키지', 'الحزم المثبتة', 'इंस्टॉल किए गए पैकेज'],
  'Riapri la configurazione': ['Reopen setup', 'Volver a la configuración', 'Rouvrir la configuration', 'Einrichtung erneut öffnen', 'Reabrir a configuração', 'Повторить настройку', '重新打开设置向导', '初期設定を開く', '초기 설정 다시 열기', 'إعادة فتح الإعداد', 'सेटअप फिर खोलें'],
  'Profilo aggiornato': ['Profile updated', 'Perfil actualizado', 'Profil mis à jour', 'Profil aktualisiert', 'Perfil atualizado', 'Профиль обновлён', '资料已更新', 'プロフィールを更新しました', '프로필이 업데이트되었습니다', 'تم تحديث الملف الشخصي', 'प्रोफ़ाइल अपडेट हो गई'],
  'Profilo aggiornato solo per questa sessione: il salvataggio su questo dispositivo non è disponibile.': ['Profile updated for this session only: saving on this device is unavailable.', 'Perfil actualizado solo para esta sesión: no se puede guardar en este dispositivo.', 'Profil mis à jour pour cette session uniquement : l’enregistrement sur cet appareil est indisponible.', 'Profil nur für diese Sitzung aktualisiert: Speichern auf diesem Gerät ist nicht verfügbar.', 'Perfil atualizado apenas para esta sessão: não é possível guardar neste dispositivo.', 'Профиль обновлён только для текущего сеанса: сохранение на этом устройстве недоступно.', '资料仅在本次会话中更新：无法保存在此设备上。', 'プロフィールは今回のセッションのみ更新されました。この端末には保存できません。', '이번 세션에만 프로필이 업데이트되었습니다. 이 기기에 저장할 수 없습니다.', 'تم تحديث الملف الشخصي لهذه الجلسة فقط: الحفظ على هذا الجهاز غير متاح.', 'प्रोफ़ाइल केवल इस सत्र के लिए अपडेट हुई: इस डिवाइस पर सहेजना उपलब्ध नहीं है।'],
};

export const profileMessages: Record<string, Record<string, string>> = Object.fromEntries(
  languages.map((language, index) => [language, Object.fromEntries(Object.entries(rows).map(([source, values]) => [source, values[index]]))]),
);
